# Bookdown Template: Title of Chapter

Replace this text with an introduction to this chapter.  

- Ensure the first line of this document starts with a single # and defines the chapter title



## Title of Sub-Section

Replace this text with discussion of sub-section topic.  

- Insert R code chunks where necessary
- Refer to RStudio Help Menu > Markdown Quick Reference for formatting guidance
- See [RMarkdown](https://bookdown.org/yihui/rmarkdown/) for more information on how `rmarkdown` works
- See [Bookdown](https://bookdown.org/yihui/bookdown/) for more information on how `bookdown` works
- The [The GitHub Page](https://github.com/rstudio/bookdown/tree/main/inst/examples) for examples of how these individual `.Rmd` files should be formatted

```{r}
str(mtcars)
```

```markdown
# Markdown chunks will be treated as raw markdown syntax, and will not be converted to HTML
```

## Title of Sub-Section

Replace this text with discussion of sub-section topic.  



## Title of Sub-Section

Replace this text with discussion of sub-section topic.  
