# Available Resources

## Contributing via GitHub

Git is a localized version control system that allows users to make changes to their files and revert to a working state whenever it is needed.  GitHub is a service that allows for sharing of git repositories, so that any number of people can make contributions to a project, while maintaining separate stable and development branches of the project files.  In addition to storing git repositories, GitHub is useful for displaying project documentation, tracking issues and feature requests, making comments, and taking part in discussions, along with offering tools for project management and some automation.  

GitHub integrates seamlessly with RStudio.  When you create a new project within RStudio, you are given the option to use git to track your repository, and to connect this local repository to an online repository on GitHub.  This goes both ways – you start a project in RStudio and later link it to a new repository on GitHub, or you can make a clone of an existing repository on GitHub for use in your local RStudio.  Because R is built on a foundation of open-source principles, GitHub has become the central location for many open-source R packages, including many of RStudio’s own packages like the Tidyverse and Shiny.   

There are also free online books that are stored and made publicly available using GitHub.  Some examples include Hadley Wickham’s “R for Data Science”, and this whitepaper you are currently reading.  If you visit the website for “R for Data Science” on a desktop browser, you will notice in the upper right side of the page a button that says, “View source” and “Edit this page”.  

Clicking on the source button will take you to the file that was used to create the HTML version of the book.  From there, you’ll be able to explore the repository of files that are used to create each individual chapter of the book.  

Clicking on the edit button will take you to a page that instructs you to, “Fork this repository”.  What this means is that you, or anyone else, can propose changes to this book.  The term “fork” simply means that you will be downloading the files to use and edit locally, and once you have made your proposed changes to the file, you will be able to submit your changes for the authors to review.  These are referred to as “pull requests”, and you can see a listing of pull requests from other users on the GitHub page for this repository by clicking on the “Pull Requests” tab.  

## WIP: Development Feedback

- Goal is to quickly introduce git and GitHub, then give an overview of how the reader can use pull requests to suggest edits to packages, projects, papers
- We can probably share the published version on GitHub, but not in a bookdown version or one that can be updated to new versions. PHUSE will likely create the final, - formatted version with a PHUSE template. That pdf can exist in the repo as a static document.
- Discussing forking, branching, pull requests are probably good, but instead of in the context of Wickham’s book, perhaps reframe this to “This is the repository for - CSRMLW” and ‘This is how you can contribute to the codebase in the repo”

